.eslintrc
.prettierignore
.prettierrc
lib/TestComponent.js
package.json
yarn.lock

In this PR I have added prettier and eslint to the project. There are now 2 new yarn scripts that make use of prettier. `yarn run prettier lib/index.js` will run prettier and rewrite an individual file following prettier formatting. `yarn run prettier:all` runs prettier in all of the relevant files of the project (ignoring package.json and node_modules). There is also a new script to run eslint on JS file: `yarn run eslint`.
Husky and lint-staged have also been used to reformat files according to prettier rules and execute eslint on JS files before they are committed.

Add prettier to ot-ui

---

lib/components/HomeBox.js
lib/components/Page.js

The Grid component from Material UI cannot take spacing and justify props when the item prop is passed (only when the container prop is passed). This was causing a console error.

Fix console errors relating to incorrect grid item props

---

package.json
yarn.lock

Some dependencies were incorrectly assigned to the devDependencies list. This PR moves them to peerDependencies, so that the package using `ot-ui` must have these dependencies.

Move several devDependencies to peerDependencies

---

lib/components/Page.spec.js
lib/setupTests.js
package.json
yarn.lock

This PR adds:
* testing setup using `jest` and `enzyme`
* script `yarn test` to run the unit tests
* script `yarn test:coverage` to collect the coverage from the unit tests
* script `yarn peer` to install peer dependencies (which the tests require)

Add unit testing setup and first test

---

lib/helpers/downloadSVG.js
lib/helpers/downloadTable.js
lib/index.js
package.json
yarn.lock

This PR:
* adds downloadTable which:
* takes an array of row objects, an array of header keys/labels, a format/extension and a filename
* triggers JSON, CSV or TSV download
* adds downloadSVG which:
* takes an svg node reference in the page
* triggers an SVG download

Add helper functions for downloading tables and charts

---

lib/components/Footer.js

Use the CSS class `fa-github-square` to use the github icon for the github link.

Use github icon for github link

---

lib/components/OtTable.js
yarn.lock

This PR adds sorting by column to the `OtTable` component. You can change to sort by another column just by clicking on another column header. You can toggle by ascending or descending sorting by clicking the same column. Also, some minor styling has been added to make the table contents scroll horizontally if they are bigger than their container.

Add sorting functionality to the OtTable component

---

lib/components/ListTooltip.js
lib/index.js

This PR adds a tooltip for rendering a list of properties, using a material-ui Popper component.

Add ListTooltip component

---

lib/components/OtTable.js

This PR adds a small help icon with tooltip on hover, per column, but only when the column definition object contains a tooltip field.

Add tooltip support

---

lib/components/DownloadSVGPlot.js
lib/index.js

This PR implements the `DownloadSVGPlot` component which renders and SVG download button to download the SVG node passed in as a prop.

Implement the DownloadSVGPlot component

---

lib/components/OtTable.js
lib/index.js

This PR exports the `Tooltip` component and also modifies the `OtTable` component to accept a new prop `verticalHeaders` to handle vertical headers.

Add option for vertical headers and export Tooltip component

---

lib/components/OtTable.js
package.json

This PR adds functionality so that `OtTable` columns can accept a custom comparator field for sorting.

Add custom comparator option to OtTable columns

---

lib/components/OtUiThemeProvider.js

Provides padding for all sections of the pages, currently only used in the header sections.

Add section padding to theme

---

.gitignore
lib/components/Footer.js
lib/components/OpenTargetsTitle.js
lib/components/OtTable.js
lib/components/OtUiThemeProvider.js
lib/components/PlotContainer.js
lib/components/typography/Heading.js
lib/components/typography/PageTitle.js
lib/components/typography/SubHeading.js
package.json

This PR updates the version of material ui and some other things:
- Update @material-ui/core and @material-ui/icons to the latest version
- Replace the deprecated values for the `variant` prop of the `Typography` component according to this https://material-ui.com/style/typography/#migration-to-typography-v2
- Updated the .gitignore file

Update material ui

---

lib/components/OtUiThemeProvider.js
lib/helpers/downloadTable.js

In the current version of OtTable, when downloading in CSV/TSV format the content for a column is matched by id. 
This doesn't work for nested fields in the data structure, resulting in a `[Object object]` string being inserted in the downloaded file for that cell.
This is also what happens when sorting columns, where fortunately we can specify a `comparator` function.
Similarly, I've added the option for an `export` function which specify what to include for that column in the downloaded file. If there is an `export` function OtTable will use that, and try to match by `id` otherwise. For example:
```
const columns = [
{
id: 'disease',
label: 'Disease',
renderCell: d => d.disease.name,
comparator: generateComparatorFromAccessor(d => d.disease.name),
export: d => d.disease.name,
}
```

Lf table download

---

lib/components/OtTable.js
lib/helpers/downloadTable.js

Short PR to address two issues in the POC QC UX review:
1. Add text label beside download buttons - "Download table as ..."
2. Add "Phase", "Status", "Source", and "Mechanism of Action" data to JSON export
Buttons label is straightforward (extra text doesn't clash with current genetics platform tables).
JSON export (point 2.) now takes into account the optional `export` callback. This is consistent with the CSV and TSV download functions. The issue was for example with the new drugs table where we pass all crossfilter data to the table (and then use the `renderCell()`, `comparator()` and `export()` options). This causes the current json download to only match few fields, but returning the full field object, hence not matching the table structure.
If the `export` option is not defined, it …

Table download labels and JSON options

---

lib/components/OtTableRF.js

I've updated OTTableRF with optional configuration for 2-tier table headers.
It can be specified/configured as:
```
<OtTableRF
headerGroups={[
{colspan:1, label:''},
{colspan:3, label:'Trial information'},
{colspan:4, label:'Drug information'},
]}
/>
```
The `headerGroups` param is optional, so won't affect tables where it's not specified.

Added option for 2-tier table header

---

lib/theme.js

This PR overrides styling of the `MuiExpansionPanel` for use in the display of credible sets.

Override MuiExpansionPanel styling

---

lib/components/OtUiThemeProvider.js
lib/theme.js

Tweak how themes work so that a user only needs to create a JS object and without having to worrying about importing `createMuiTheme`.

Tweak how themes work

---

lib/components/OtTableRF.js

Rough implementation of pagination for OtTableRF, tested with the evidence literature code.
Still very much in progress but would be good to get some feedback as I know we're looking at reloading queries in other parts of the platform.
Example use:
```
const paginationCallback = (page, pageSize) => {
this.setState({ from: (page * (pageSize || size)) });
}
// .....
return(
<OtTableRF
loading={false}
error={false}
columns={columns}
data={data.rows}
serverPagination={true}
totalPagination={data.textMiningCount}
callPagination={paginationCallback}
/>
)
```

Add initial options for server side pagination
